name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-21.05
      - uses: cachix/cachix-action@v10
        with:
          name: elm-csv
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: niv
      - run: nix-shell --pure --run 'true'
      - run: ./ci.sh
