name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      - uses: cachix/cachix-action@v8
        with:
          name: niv
          skipPush: true
      - run: nix-shell --pure --run 'true'
      - run: ./ci.sh
